#scripts are called from the codebase folder, so only one dot
logindata_filepath: "./DATA_GYM/sanitized_login_data.csv"
userdata_filepath: "./DATA_GYM/sanitized_customer_base.csv"
data_output_dir: "./results/regularity/statistics/"


experiments:
  ex_1:
    stat: "apen"
    params:
      m: 2
      r: 0.2
      detrend: True
      sigma_units: True

  ex_2:
    stat: "apen"
    params:
      m: 3
      r: 0.2
      detrend: True
      sigma_units: True
          
  ex_3:
    stat: "sampen"
    params:
      m: 2
      r: 0.2
      detrend: True
      sigma_units: True

  ex_4:
    stat: "sampen"
    params:
      m: 3
      r: 0.2
      detrend: True
      sigma_units: True

  ex_5:
    stat: "permen"
    params:
      n: 3
      lag: 1
      normalize: True

  ex_6:
    stat: "permen"
    params:
      n: 5
      lag: 1
      normalize: True